"""Update session table and add user id column

Revision ID: 0f00b79ed25f
Revises: a04e0e4e1033
Create Date: 2026-03-25 10:41:47.886986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f00b79ed25f'
down_revision: Union[str, Sequence[str], None] = 'a04e0e4e1033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_session', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_active_session_id'), table_name='active_session')
    op.create_foreign_key(None, 'active_session', 'customers_details', ['user_id'], ['id'])
    op.drop_index(op.f('ix_customers_details_id'), table_name='customers_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_details_id'), 'customers_details', ['id'], unique=True)
    op.drop_constraint(None, 'active_session', type_='foreignkey')
    op.create_index(op.f('ix_active_session_id'), 'active_session', ['id'], unique=False)
    op.drop_column('active_session', 'user_id')
    op.create_table('cart',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('cart_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('cart_product_id_fkey'), ondelete='CASCADE')
    )
    op.create_index(op.f('cart_product_id_idx'), 'cart', ['product_id'], unique=True)
    op.create_table('order_details',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordered_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('check_cart_quantity')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('order_details_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_details_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_details_pkey'))
    )
    # ### end Alembic commands ###
