"""Add relationship and setting to handle user deletion

Revision ID: 15736f623998
Revises: d403531f9aed
Create Date: 2026-03-20 16:18:50.800626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15736f623998'
down_revision: Union[str, Sequence[str], None] = 'd403531f9aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'seller_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('products_seller_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'customers_details', ['seller_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_seller_id_fkey'), 'products', 'customers_details', ['seller_id'], ['id'])
    op.alter_column('products', 'seller_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('session_id',
    sa.Column('sid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sess', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expire', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sid', name=op.f('session_id_pkey'))
    )
    op.create_index(op.f('IDX_session_expire'), 'session_id', ['expire'], unique=False)
    op.create_table('cart',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('cart_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('cart_product_id_fkey'), ondelete='CASCADE')
    )
    op.create_index(op.f('cart_product_id_idx'), 'cart', ['product_id'], unique=True)
    op.create_table('order_details',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordered_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('check_cart_quantity')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('order_details_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_details_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_details_pkey'))
    )
    # ### end Alembic commands ###
