"""Add delete_at and update types of columns

Revision ID: a04e0e4e1033
Revises: f3e8cc88361d
Create Date: 2026-03-25 08:03:55.549735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a04e0e4e1033'
down_revision: Union[str, Sequence[str], None] = 'f3e8cc88361d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=True)
    op.drop_column('products', 'deleted_at')
    op.create_table('order_details',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordered_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('check_cart_quantity')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('order_details_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_details_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_details_pkey'))
    )
    op.create_table('cart',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('cart_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('cart_product_id_fkey'), ondelete='CASCADE')
    )
    op.create_index(op.f('cart_product_id_idx'), 'cart', ['product_id'], unique=True)
    # ### end Alembic commands ###
