"""add cart table and update relationship

Revision ID: b44d680cec2f
Revises: 0f00b79ed25f
Create Date: 2026-03-25 13:24:26.742797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b44d680cec2f'
down_revision: Union[str, Sequence[str], None] = '0f00b79ed25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['customers_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'user_id', name='unique_product_user_cart')
    )
    op.create_index(op.f('ix_customer_cart_product_id'), 'customer_cart', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_cart_user_id'), 'customer_cart', ['user_id'], unique=False)
    op.drop_index(op.f('cart_product_id_idx'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_details',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordered_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('check_cart_quantity')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('order_details_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_details_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_details_pkey'))
    )
    op.create_table('cart',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('cart_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('cart_product_id_fkey'), ondelete='CASCADE')
    )
    op.create_index(op.f('cart_product_id_idx'), 'cart', ['product_id'], unique=True)
    op.drop_index(op.f('ix_customer_cart_user_id'), table_name='customer_cart')
    op.drop_index(op.f('ix_customer_cart_product_id'), table_name='customer_cart')
    op.drop_table('customer_cart')
    # ### end Alembic commands ###
