"""init

Revision ID: d403531f9aed
Revises: 
Create Date: 2026-03-19 20:55:40.584539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd403531f9aed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers_details', 'address',
                    existing_type=sa.TEXT(),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=255),
                    existing_nullable=False)
    op.alter_column('customers_details', 'email',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('customers_details', 'password',
                    existing_type=sa.TEXT(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=False)
    op.drop_constraint(op.f('customers_details_email_key'),
                       'customers_details', type_='unique')
    op.drop_constraint(op.f('customers_details_phone_key'),
                       'customers_details', type_='unique')
    op.create_index(op.f('ix_customers_details_email'),
                    'customers_details', ['email'], unique=True)
    op.create_index(op.f('ix_customers_details_id'),
                    'customers_details', ['id'], unique=True)
    op.add_column('products', sa.Column('created_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('products', 'description',
                    existing_type=sa.TEXT(),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
                    existing_nullable=False)
    op.alter_column('products', 'price',
                    existing_type=sa.REAL(),
                    type_=sa.Numeric(scale=2),
                    existing_nullable=False)
    op.alter_column('products', 'seller_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'seller_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('products', 'price',
                    existing_type=sa.Numeric(scale=2),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.alter_column('products', 'description',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(
                        length=1000),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.drop_column('products', 'created_at')
    op.drop_index(op.f('ix_customers_details_id'),
                  table_name='customers_details')
    op.drop_index(op.f('ix_customers_details_email'),
                  table_name='customers_details')
    op.create_unique_constraint(op.f('customers_details_phone_key'), 'customers_details', [
                                'phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customers_details_email_key'), 'customers_details', [
                                'email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers_details', 'password',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('customers_details', 'email',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('customers_details', 'address',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.create_table('order_details',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('product_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('customer_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('quantity', sa.INTEGER(), server_default=sa.text(
                        '1'), autoincrement=False, nullable=True),
                    sa.Column('payment_status', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('payment_mode', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('ordered_on', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=True),
                    sa.CheckConstraint(
                        'quantity > 0', name=op.f('check_cart_quantity')),
                    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f(
                        'order_details_customer_id_fkey')),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f(
                        'order_details_product_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('order_details_pkey'))
                    )
    op.create_table('cart',
                    sa.Column('product_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('customer_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('quantity', sa.INTEGER(), server_default=sa.text(
                        '1'), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['customer_id'], ['customers_details.id'], name=op.f('cart_customer_id_fkey')),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f(
                        'cart_product_id_fkey'), ondelete='CASCADE')
                    )
    op.create_index(op.f('cart_product_id_idx'),
                    'cart', ['product_id'], unique=True)
    op.create_table('session_id',
                    sa.Column('sid', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('sess', postgresql.JSON(
                        astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.Column('expire', postgresql.TIMESTAMP(precision=6),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'sid', name=op.f('session_id_pkey'))
                    )
    op.create_index(op.f('IDX_session_expire'),
                    'session_id', ['expire'], unique=False)
    # ### end Alembic commands ###
