"""create session table

Revision ID: f3e8cc88361d
Revises: 15736f623998
Create Date: 2026-03-22 09:33:27.757557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3e8cc88361d'
down_revision: Union[str, Sequence[str], None] = '15736f623998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_session_expire_at'), 'active_session', ['expire_at'], unique=False)
    op.create_index(op.f('ix_active_session_id'), 'active_session', ['id'], unique=False)
    op.drop_index(op.f('IDX_session_expire'), table_name='session_id')
    op.drop_table('session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_details',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordered_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('check_cart_quantity')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('order_details_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_details_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_details_pkey'))
    )
    op.create_table('session_id',
    sa.Column('sid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sess', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expire', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sid', name=op.f('session_id_pkey'))
    )
    op.create_index(op.f('IDX_session_expire'), 'session_id', ['expire'], unique=False)
    op.create_table('cart',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers_details.id'], name=op.f('cart_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('cart_product_id_fkey'), ondelete='CASCADE')
    )
    op.create_index(op.f('cart_product_id_idx'), 'cart', ['product_id'], unique=True)
    op.drop_index(op.f('ix_active_session_id'), table_name='active_session')
    op.drop_index(op.f('ix_active_session_expire_at'), table_name='active_session')
    op.drop_table('active_session')
    # ### end Alembic commands ###
